# Generated by Django 2.2 on 2021-07-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'published'), ('title', 'price', 'rubric')},
        ),
    ]
